### ISSUE TITLE
OSError: [Errno 5] EIO

### ISSUE THREAD

**Issue by lukasvavrous** [chrisbalmer/micropython-si7021#1]
I got from example.py this error
Serial:              36457414120261716
Identifier:          unknown
Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
  File "si7021.py", line 37, in temperature
  File "si7021.py", line 72, in _get_data
OSError: [Errno 5] EIO

It crashes on ->   self.i2c.readfrom_into(self.address, data)

Any tips?

**Comment by tyeth** [comment]
Hey I've not tested it on micropython, but on circuitpython I needed to use i2c.try_lock() and .unlock()

I've commited it here https://github.com/tyeth/micropython-si7021/blob/master/si7021.py
and these are the changes I made after getting this error: 
RuntimeError: Function requires lock
https://github.com/tyeth/micropython-si7021/commit/71e0347c33fe22b99fe8a538196bed7def889646
